FROM rust:1.47 AS miracl-core-bn254-rust
LABEL maintainer="burkh4rt"

WORKDIR /usr/src/
ENV USER root

RUN git clone https://github.com/burkh4rt/miracl-core.git \
    && git --git-dir=./miracl-core/.git checkout -fq c340052 \
    && mkdir ./rust-core/ \
    && cp ./miracl-core/rust/* ./rust-core/ \
    && rm -rf ./miracl-core/ \
    && cd rust-core/ \
    && sed -i '349,353d' config64.py \
    && sed -i '348 i\    for x in [28,0]:' config64.py \
    && python3 config64.py


FROM rust:1.47
LABEL maintainer="burkh4rt"

WORKDIR /usr/src/

COPY --from=miracl-core-bn254-rust /usr/src/rust-core ./rust-core/
COPY . .

RUN cargo build
CMD cargo run